export const GET_ALL_POSTS_REQUEST =  "GET_ALL_POSTS_REQUEST"
export const GET_ALL_POSTS_SUCCESS =  "GET_ALL_POSTS_SUCCESS"
export const GET_ALL_POSTS_FAIL =  "GET_ALL_POSTS_FAIL"
export const GET_ALL_POSTS_RESET =  "GET_ALL_POSTS_RESET"

export const POST_POSTS_REQUEST =  "POST_POSTS_REQUEST"
export const POST_POSTS_SUCCESS =  "POST_POSTS_SUCCESS"
export const POST_POSTS_FAIL =  "POST_POSTS_FAIL"
export const POST_POSTS_RESET =  "POST_POSTS_RESET"
